name: test

on:
  pull_request:
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
      - name: Install poetry
        run: pipx install poetry
      - name: Install Library
        run: |
           poetry install
           poetry run pre-commit install
      - name: Run Test
        run: make test
      - name: Run Linters
        run: make lint
      - name: Check Documentation
        run: make docs
