name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    name: "Bump version and create changelog with commitizen"
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{"{{"}} secrets.GITHUB_TOKEN {{"}}"}}
      # Taken from https://github.com/orgs/community/discussions/26560
      - name: Setup Git
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install poetry 1.3
        run: |
          pipx install 'poetry<1.4'
          poetry install
      - id: cz
        name: Create bump and changelog
        run: |
          poetry run cz -nr 21 bump --yes
          git push origin HEAD --tags
      - id: doc
        name: Update documentation
        run: |
          poetry run mkdocs gh-deploy -f docs/mkdocs.yml
