name: Apply cookiecutter from template

on: [push]

permissions: write-all

jobs:
  bake:
    if: ${{ !contains (github.repository, '/cookiecutter-pypackage') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Install cookiecutter
        run: pipx install cookiecutter
      - run: echo "REPOSITORY_NAME=custom-package" >> $GITHUB_ENV
        shell: bash
      - name: Run cookiecutter
        run: | 
          cookiecutter --no-input .
          ls -A | grep -v $REPOSITORY_NAME | grep -v .git | xargs -n 1 rm -rf
          mv $REPOSITORY_NAME/* .
          rm -r $REPOSITORY_NAME
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Running initial cookiecutter"
          push_options: --force
