name: Apply cookiecutter from template

on: [push]

permissions: write-all

jobs:
  bake:
    if: ${{ !contains (github.repository, '/cookiecutter-pypackage') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Install cookiecutter
        run: pipx install cookiecutter
      - name: Run cookiecutter
        env:
          # This matches the cookiecutter `package_name` as github replaces ` ` for `-` automatically
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          DESCRIPTION: ${{ github.event.repository.description }}
          AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
          AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
          TEMP_DIR_NAME: "a_very_long_name_that_no_one_in_their_right_mind_would_ever_think_to_use_as_top_level_in_a_python_package"
        run: | 
          cookiecutter --no-input . \
            package_title="${REPOSITORY_NAME}" \
            package_description="${DESCRIPTION}" \
            author_name="${AUTHOR_NAME}" \
            author_email="${AUTHOR_EMAIL}"
          ls -A | grep -v ${REPOSITORY_NAME} | grep -v .git | xargs -n 1 rm -rf
          mv ${REPOSITORY_NAME} ${TEMP_DIR_NAME}
          shopt -s dotglob
          mv ${TEMP_DIR_NAME}/* .
          rm -r ${TEMP_DIR_NAME}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Running initial cookiecutter"
          push_options: --force
