name: Apply cookiecutter from template

on: [push]

permissions: write-all

jobs:
  check_secret_ingredients:
    if: ${{ !contains (github.repository, '/cookiecutter-pypackage') }}
    runs-on: ubuntu-latest
    env: 
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: PAT Secret is set
        run: |
          [ ! $PERSONAL_ACCESS_TOKEN = "" ]

  bake:
    runs-on: ubuntu-latest
    needs: check_secret_ingredients
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Install cookiecutter
        run: pipx install cookiecutter
      - name: Run cookiecutter
        env:
          # This matches the cookiecutter `package_name` as github replaces ` ` for `-` automatically
          REPOSITORY_NAME: ${{ github.event.repository.name }}
          DESCRIPTION: ${{ github.event.repository.description }}
          AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
          AUTHOR_EMAIL: ${{ github.event.head_commit.author.email }}
          AUTHOR_GH_HANDLE: ${{ github.event.repository.owner.login }}
          TEMP_DIR_NAME: "a_very_long_name_that_no_one_in_their_right_mind_would_ever_think_to_use_as_top_level_in_a_python_package"
        run: | 
          cookiecutter --no-input . \
            package_title="${REPOSITORY_NAME}" \
            package_description="${DESCRIPTION}" \
            author_name="${AUTHOR_NAME}" \
            author_email="${AUTHOR_EMAIL}" \
            github_username="${AUTHOR_GH_HANDLE}"
          find . -not -path "./${REPOSITORY_NAME}/*" -not -path "./.git/*" -type f -delete
          find . -type d -empty -delete
          mv ${REPOSITORY_NAME} ${TEMP_DIR_NAME}
          shopt -s dotglob
          mv ${TEMP_DIR_NAME}/* .
          rm -r ${TEMP_DIR_NAME}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Running initial cookiecutter"
          push_options: --force
    
  decorate:
    needs: bake
    runs-on: ubuntu-latest
    steps:
      - name: Setup Squash-Merge
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              has_projects: false,
              has_wiki: false,
              allow_merge_commit: false,
              allow_rebase_merge: false,
              allow_squash_merge: true,
              delete_branch_on_merge: true,
              squash_merge_commit_title: "PR_TITLE",
              squash_merge_commit_message: "PR_BODY",
            });
      - name: Setup Branch Protection
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.repos.updateBranchProtection({
              owner: context.repo.owner,
              repo: context.repo.repo,
              branch: "main",
              required_status_checks: {
                strict: true,
                contexts: []
              },
              enforce_admins: false,
              required_pull_request_reviews: null,
              restrictions: null,
            });
      - name: Setup Pages
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.repos.createPagesSite({
              owner: context.repo.owner,
              repo: context.repo.repo,
              source: {
                branch: "gh-pages",
              },
            });
