name: Check Build

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  make-and-bake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath
      - name: Install poetry
        run: pipx install poetry
      - name: Install cookiecutter
        run: pipx install cookiecutter
      - name: Run cookiecutter
        run: make test
